import { MartialArt, AllRanks } from '../types';

export const initialMartialArts: MartialArt[] = [
    {
        id: 1,
        name: 'Karate Tradicional',
        ranks: [
            AllRanks.WHITE,
            AllRanks.YELLOW,
            AllRanks.RED,
            AllRanks.ORANGE,
            AllRanks.GREEN,
            AllRanks.PURPLE,
            AllRanks.BROWN,
            AllRanks.BLACK,
        ],
        usesDegrees: true,
        maxDegrees: 2,
        promotionRequirements: {
            [AllRanks.WHITE]: 30,
            [AllRanks.YELLOW]: 30,
            [AllRanks.RED]: 60,
            [AllRanks.ORANGE]: 90,
            [AllRanks.GREEN]: 90,
            [AllRanks.PURPLE]: 120,
            [AllRanks.BROWN]: 120,
            [AllRanks.BLACK]: 0,
        },
    },
    {
        id: 2,
        name: 'Karate de Contato',
        ranks: [
            AllRanks.WHITE,
            AllRanks.YELLOW,
            AllRanks.ORANGE,
            AllRanks.GREEN,
            AllRanks.BLUE,
            AllRanks.PURPLE,
            AllRanks.BROWN,
            AllRanks.BLACK,
        ],
        usesDegrees: true,
        maxDegrees: 2,
        promotionRequirements: {
            [AllRanks.WHITE]: 40,
            [AllRanks.YELLOW]: 40,
            [AllRanks.ORANGE]: 70,
            [AllRanks.GREEN]: 100,
            [AllRanks.BLUE]: 100,
            [AllRanks.PURPLE]: 120,
            [AllRanks.BROWN]: 120,
            [AllRanks.BLACK]: 0,
        },
    },
    {
        id: 3,
        name: 'Jiu-Jitsu',
        ranks: [
            AllRanks.WHITE,
            AllRanks.GRAY,
            AllRanks.YELLOW,
            AllRanks.ORANGE,
            AllRanks.GREEN,
            AllRanks.BLUE,
            AllRanks.PURPLE,
            AllRanks.BROWN,
            AllRanks.BLACK,
        ],
        usesDegrees: true,
        maxDegrees: 4,
        promotionRequirements: {
            [AllRanks.WHITE]: 120,
            [AllRanks.GRAY]: 120,
            [AllRanks.YELLOW]: 120,
            [AllRanks.ORANGE]: 120,
            [AllRanks.GREEN]: 120,
            [AllRanks.BLUE]: 150,
            [AllRanks.PURPLE]: 150,
            [AllRanks.BROWN]: 180,
            [AllRanks.BLACK]: 0,
        },
    }
];