import { Student, AdminUser, StudentStatus, Gender, TraditionalKarateRank, ContactKarateRank, JiuJitsuRank } from '../types';

export const adminUser: AdminUser = {
  username: 'admin',
  role: 'admin',
};

export const initialStudents: Student[] = [
  {
    id: 1,
    username: 'ryu.h',
    password: 'password123',
    status: StudentStatus.ACTIVE,
    fullName: 'Ryu Hoshi',
    birthDate: '1964-07-21',
    gender: Gender.MALE,
    photo: 'https://picsum.photos/seed/ryu/200/200',
    internalRegistry: 'JKD-001',
    enrollmentDate: '2022-01-15',
    contactPhone: '(11) 98765-4321',
    dojo: 'Matriz',
    observations: 'Aluno dedicado, focado no aprimoramento do Hadouken.',
    traditionalKarateRank: TraditionalKarateRank.BLACK,
    traditionalKarateDegree: 2,
    contactKarateRank: ContactKarateRank.BLACK,
    contactKarateDegree: 1,
    jiuJitsuRank: JiuJitsuRank.BROWN,
    jiuJitsuDegree: 3,
  },
  {
    id: 2,
    username: 'chun.li',
    password: 'password456',
    status: StudentStatus.ACTIVE,
    fullName: 'Chun-Li',
    birthDate: '1968-03-01',
    gender: Gender.FEMALE,
    photo: 'https://picsum.photos/seed/chunli/200/200',
    internalRegistry: 'JKD-002',
    enrollmentDate: '2023-03-10',
    contactPhone: '(21) 91234-5678',
    dojo: 'Filial Centro',
    observations: 'Extremamente ágil e forte. Especialista em chutes.',
    traditionalKarateRank: TraditionalKarateRank.BROWN,
    traditionalKarateDegree: 1,
    contactKarateRank: ContactKarateRank.PURPLE,
    contactKarateDegree: 2,
    jiuJitsuRank: JiuJitsuRank.BLUE,
    jiuJitsuDegree: 4,
  },
  {
    id: 3,
    username: 'ken.m',
    password: 'password789',
    status: StudentStatus.ACTIVE,
    fullName: 'Ken Masters',
    birthDate: '1965-02-14',
    gender: Gender.MALE,
    photo: 'https://picsum.photos/seed/ken/200/200',
    internalRegistry: 'JKD-003',
    enrollmentDate: '2024-05-20',
    contactPhone: '(11) 99999-8888',
    dojo: 'Matriz',
    observations: 'Estilo de luta vistoso e eficaz.',
    traditionalKarateRank: TraditionalKarateRank.BLACK,
    traditionalKarateDegree: 2,
    contactKarateRank: ContactKarateRank.BROWN,
    contactKarateDegree: 0,
    jiuJitsuRank: JiuJitsuRank.PURPLE,
    jiuJitsuDegree: 1,
  },
  {
    id: 4,
    username: 'sakura.k',
    password: 'password101',
    status: StudentStatus.ACTIVE,
    fullName: 'Sakura Kasugano',
    birthDate: new Date(new Date().setMonth(new Date().getMonth(), 15)).toISOString().split('T')[0], // Birthday this month
    gender: Gender.FEMALE,
    photo: 'https://picsum.photos/seed/sakura/200/200',
    internalRegistry: 'JKD-004',
    enrollmentDate: '2024-06-01',
    contactPhone: '(11) 98888-7777',
    dojo: 'Filial Zona Sul',
    observations: 'Grande potencial e entusiasmo.',
    traditionalKarateRank: TraditionalKarateRank.GREEN,
    traditionalKarateDegree: 0,
    contactKarateRank: ContactKarateRank.BLUE,
    contactKarateDegree: 0,
    jiuJitsuRank: JiuJitsuRank.WHITE,
    jiuJitsuDegree: 2,
  },
  {
    id: 5,
    username: 'zangief.r',
    password: 'password112',
    status: StudentStatus.INACTIVE,
    fullName: 'Zangief',
    birthDate: '1956-06-01',
    gender: Gender.MALE,
    photo: 'https://picsum.photos/seed/zangief/200/200',
    internalRegistry: 'JKD-005',
    enrollmentDate: '2023-01-30',
    contactPhone: '(51) 97777-6666',
    dojo: 'Matriz',
    observations: 'Força bruta incomparável.',
    traditionalKarateRank: TraditionalKarateRank.ORANGE,
    traditionalKarateDegree: 1,
    contactKarateRank: ContactKarateRank.GREEN,
    contactKarateDegree: 1,
    jiuJitsuRank: JiuJitsuRank.GRAY,
    jiuJitsuDegree: 0,
  },
  {
    id: 6,
    username: 'cammy.w',
    password: 'password131',
    status: StudentStatus.ACTIVE,
    fullName: 'Cammy White',
    birthDate: '1974-01-06',
    gender: Gender.FEMALE,
    photo: 'https://picsum.photos/seed/cammy/200/200',
    internalRegistry: 'JKD-006',
    enrollmentDate: '2024-04-10',
    contactPhone: '(48) 96666-5555',
    dojo: 'Filial Centro',
    observations: 'Rápida e precisa.',
    traditionalKarateRank: TraditionalKarateRank.PURPLE,
    traditionalKarateDegree: 0,
    contactKarateRank: ContactKarateRank.PURPLE,
    contactKarateDegree: 0,
    jiuJitsuRank: JiuJitsuRank.BLUE,
    jiuJitsuDegree: 2,
  },
  {
    id: 7,
    username: 'dhalsim.i',
    password: 'password415',
    status: StudentStatus.ACTIVE,
    fullName: 'Dhalsim',
    birthDate: '1952-11-22',
    gender: Gender.MALE,
    photo: 'https://picsum.photos/seed/dhalsim/200/200',
    internalRegistry: 'JKD-007',
    enrollmentDate: '2024-02-18',
    contactPhone: '(85) 95555-4444',
    dojo: 'Filial Zona Sul',
    observations: 'Flexibilidade e controle da respiração.',
    traditionalKarateRank: TraditionalKarateRank.BROWN,
    traditionalKarateDegree: 2,
    contactKarateRank: ContactKarateRank.BROWN,
    contactKarateDegree: 2,
    jiuJitsuRank: JiuJitsuRank.BLACK,
    jiuJitsuDegree: 4,
  },
  {
    id: 8,
    username: 'vega.s',
    password: 'password161',
    status: StudentStatus.ACTIVE,
    fullName: 'Vega',
    birthDate: '1967-01-27',
    gender: Gender.MALE,
    photo: 'https://picsum.photos/seed/vega/200/200',
    internalRegistry: 'JKD-008',
    enrollmentDate: new Date(new Date().setMonth(new Date().getMonth() - 2, 5)).toISOString().split('T')[0], // Due payment
    contactPhone: '(71) 94444-3333',
    dojo: 'Matriz',
    observations: 'Usa uma garra para lutar.',
    traditionalKarateRank: TraditionalKarateRank.RED,
    traditionalKarateDegree: 0,
    contactKarateRank: ContactKarateRank.ORANGE,
    contactKarateDegree: 1,
    jiuJitsuRank: JiuJitsuRank.YELLOW,
    jiuJitsuDegree: 3,
  },
  {
    id: 9,
    username: 'ibuki.n',
    password: 'password718',
    status: StudentStatus.ACTIVE,
    fullName: 'Ibuki',
    birthDate: new Date(new Date().setMonth(new Date().getMonth(), 28)).toISOString().split('T')[0], // Birthday in 12 days
    gender: Gender.FEMALE,
    photo: 'https://picsum.photos/seed/ibuki/200/200',
    internalRegistry: 'JKD-009',
    enrollmentDate: '2024-07-01',
    contactPhone: '(31) 93333-2222',
    dojo: 'Filial Centro',
    observations: 'Estilo de ninjutsu.',
    traditionalKarateRank: TraditionalKarateRank.YELLOW,
    traditionalKarateDegree: 0,
    contactKarateRank: ContactKarateRank.YELLOW,
    contactKarateDegree: 0,
    jiuJitsuRank: JiuJitsuRank.GREEN,
    jiuJitsuDegree: 1,
  },
  {
    id: 10,
    username: 'balrog.b',
    password: 'password192',
    status: StudentStatus.INACTIVE,
    fullName: 'Balrog',
    birthDate: '1968-09-04',
    gender: Gender.MALE,
    photo: 'https://picsum.photos/seed/balrog/200/200',
    internalRegistry: 'JKD-010',
    enrollmentDate: '2023-11-05',
    contactPhone: '(61) 92222-1111',
    dojo: 'Matriz',
    observations: 'Boxeador profissional.',
    traditionalKarateRank: TraditionalKarateRank.WHITE,
    traditionalKarateDegree: 0,
    contactKarateRank: ContactKarateRank.WHITE,
    contactKarateDegree: 0,
    jiuJitsuRank: JiuJitsuRank.WHITE,
    jiuJitsuDegree: 0,
  },
  {
    id: 11,
    username: 'juri.h',
    password: 'password202',
    status: StudentStatus.ACTIVE,
    fullName: 'Juri Han',
    birthDate: '1985-01-01',
    gender: Gender.FEMALE,
    photo: 'https://picsum.photos/seed/juri/200/200',
    internalRegistry: 'JKD-011',
    enrollmentDate: new Date(new Date().setMonth(new Date().getMonth() - 1, 1)).toISOString().split('T')[0], // Due payment
    contactPhone: '(92) 91111-0000',
    dojo: 'Filial Zona Sul',
    observations: 'Possui o Feng Shui Engine no olho esquerdo.',
    traditionalKarateRank: TraditionalKarateRank.PURPLE,
    traditionalKarateDegree: 1,
    contactKarateRank: ContactKarateRank.BLUE,
    contactKarateDegree: 2,
    jiuJitsuRank: JiuJitsuRank.PURPLE,
    jiuJitsuDegree: 4,
  },
  {
    id: 12,
    username: 'akuma.g',
    password: 'password666',
    status: StudentStatus.ACTIVE,
    fullName: 'Akuma',
    birthDate: '1950-12-25',
    gender: Gender.MALE,
    photo: 'https://picsum.photos/seed/akuma/200/200',
    internalRegistry: 'JKD-012',
    enrollmentDate: '2024-03-15',
    contactPhone: '(27) 90000-9999',
    dojo: 'Matriz',
    observations: 'Mestre do Satsui no Hado.',
    traditionalKarateRank: TraditionalKarateRank.BLACK,
    traditionalKarateDegree: 2,
    contactKarateRank: ContactKarateRank.BLACK,
    contactKarateDegree: 2,
    jiuJitsuRank: JiuJitsuRank.BLACK,
    jiuJitsuDegree: 4,
  }
];